name: "Generating Images"
description: "Creates Images with Repo Stats to post on Roblox Forum"
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ${{ github.token }}
runs:
  using: node16
  main: "dist/index.js"