name: 'Roblox Forum Github Stats Images'
run-name: 'Generating Images'
on:
  workflow_dispatch:
    
  schedule:
    - cron:  '*/1 * * * *'
jobs:
  Generating_Images:
    name: 'Generating Images'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v



